/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/app/': RouteRecordInfo<'/app/', '/app', Record<never, never>, Record<never, never>>,
    '/cloudsync/': RouteRecordInfo<'/cloudsync/', '/cloudsync', Record<never, never>, Record<never, never>>,
    '/control/': RouteRecordInfo<'/control/', '/control', Record<never, never>, Record<never, never>>,
    '/debug/': RouteRecordInfo<'/debug/', '/debug', Record<never, never>, Record<never, never>>,
    '/epg/': RouteRecordInfo<'/epg/', '/epg', Record<never, never>, Record<never, never>>,
    '/epg/epg-source-add/': RouteRecordInfo<'/epg/epg-source-add/', '/epg/epg-source-add', Record<never, never>, Record<never, never>>,
    '/epg/epg-source-detail/[idx]': RouteRecordInfo<'/epg/epg-source-detail/[idx]', '/epg/epg-source-detail/:idx', { idx: ParamValue<true> }, { idx: ParamValue<false> }>,
    '/epg/epg-source-list/': RouteRecordInfo<'/epg/epg-source-list/', '/epg/epg-source-list', Record<never, never>, Record<never, never>>,
    '/iptv/': RouteRecordInfo<'/iptv/', '/iptv', Record<never, never>, Record<never, never>>,
    '/iptv/channel-alias/': RouteRecordInfo<'/iptv/channel-alias/', '/iptv/channel-alias', Record<never, never>, Record<never, never>>,
    '/iptv/favorites/': RouteRecordInfo<'/iptv/favorites/', '/iptv/favorites', Record<never, never>, Record<never, never>>,
    '/iptv/iptv-source-add/': RouteRecordInfo<'/iptv/iptv-source-add/', '/iptv/iptv-source-add', Record<never, never>, Record<never, never>>,
    '/iptv/iptv-source-detail/[idx]': RouteRecordInfo<'/iptv/iptv-source-detail/[idx]', '/iptv/iptv-source-detail/:idx', { idx: ParamValue<true> }, { idx: ParamValue<false> }>,
    '/iptv/iptv-source-list/': RouteRecordInfo<'/iptv/iptv-source-list/', '/iptv/iptv-source-list', Record<never, never>, Record<never, never>>,
    '/log/': RouteRecordInfo<'/log/', '/log', Record<never, never>, Record<never, never>>,
    '/player/': RouteRecordInfo<'/player/', '/player', Record<never, never>, Record<never, never>>,
    '/README': RouteRecordInfo<'/README', '/README', Record<never, never>, Record<never, never>>,
    '/theme/': RouteRecordInfo<'/theme/', '/theme', Record<never, never>, Record<never, never>>,
    '/ui/': RouteRecordInfo<'/ui/', '/ui', Record<never, never>, Record<never, never>>,
    '/update/': RouteRecordInfo<'/update/', '/update', Record<never, never>, Record<never, never>>,
  }
}
